name: tqc
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex
  - blas
  - ca-certificates
  - certifi
  - cffi
  - cudatoolkit
  - freetype
  - intel-openmp
  - jpeg
  - libedit
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libpng
  - libstdcxx-ng
  - libtiff
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ncurses
  - ninja
  - numpy
  - numpy-base
  - olefile
  - openssl
  - pillow
  - pip
  - pycparser
  - python
  - pytorch
  - readline
  - setuptools
  - six
  - sqlite
  - tk
  - torchvision
  - wheel
  - xz
  - zlib
  - zstd
  - pip:
    - pyglet
    - scipy
